// web-solid/src/components/reasoning/ModelComparison.tsx
import { createMemo, Show, For } from 'solid-js'
import { chatState } from '../../stores/chat'

export function ModelComparison() {
  const modelOutputs = createMemo(() =>
    chatState.reasoningSteps.filter(
      (s) => s.event_type === 'step_complete' && s.step_name.startsWith('model_'),
    ),
  )

  const consensusResult = createMemo(() =>
    chatState.reasoningSteps.find(
      (s) => s.event_type === 'consensus' && s.step_name === 'complete',
    ),
  )

  return (
    <Show when={modelOutputs().length > 0} fallback={
      <div class="flex-1 flex items-center justify-center text-xs p-4" style={{ color: 'var(--color-text-muted)' }}>
        <div class="text-center">
          <p class="mb-1">No multi-model comparison data</p>
          <p style={{ opacity: 0.6 }}>Use Debate or Research mode with consensus strategy to compare models</p>
        </div>
      </div>
    }>
      <div class="flex-1 overflow-y-auto p-3 space-y-3">
        <div
          class="grid gap-3"
          style={{ 'grid-template-columns': `repeat(${Math.min(modelOutputs().length, 3)}, 1fr)` }}
        >
          <For each={modelOutputs()}>
            {(output, i) => (
              <div class="rounded-lg overflow-hidden" style={{ border: '1px solid var(--color-border)' }}>
                <div
                  class="px-3 py-1.5 flex items-center justify-between"
                  style={{
                    background: 'var(--color-surface-hover)',
                    'border-bottom': '1px solid var(--color-border)',
                  }}
                >
                  <span class="text-xs font-medium" style={{ color: 'var(--color-text-primary)' }}>
                    {output.model || `Model ${i() + 1}`}
                  </span>
                  <Show when={output.metadata?.tokens}>
                    <span style={{ 'font-size': '10px', color: 'var(--color-text-muted)' }}>
                      {output.metadata.tokens as number} tok
                    </span>
                  </Show>
                </div>
                <div
                  class="p-3 text-xs leading-relaxed whitespace-pre-wrap overflow-y-auto"
                  style={{ color: 'var(--color-text-secondary)', 'max-height': '300px' }}
                >
                  {output.content}
                </div>
              </div>
            )}
          </For>
        </div>

        <Show when={consensusResult()}>
          {(result) => (
            <div class="rounded-lg overflow-hidden" style={{ border: '1px solid oklch(0.72 0.17 162 / 0.3)' }}>
              <div
                class="px-3 py-1.5"
                style={{
                  background: 'oklch(0.72 0.17 162 / 0.1)',
                  'border-bottom': '1px solid oklch(0.72 0.17 162 / 0.2)',
                }}
              >
                <span class="text-xs font-medium" style={{ color: 'var(--color-accent)' }}>
                  Consensus Synthesis
                </span>
              </div>
              <div class="p-3 text-xs leading-relaxed whitespace-pre-wrap" style={{ color: 'var(--color-text-secondary)' }}>
                {result().content}
              </div>
            </div>
          )}
        </Show>
      </div>
    </Show>
  )
}

// web/src/components/reasoning/ModelComparison.tsx
import { useMemo } from 'react'
import { useChatStore } from '../../stores/chat'

export function ModelComparison() {
  const reasoningSteps = useChatStore((s) => s.reasoningSteps)

  // Find consensus/model comparison steps
  const modelOutputs = useMemo(() => {
    return reasoningSteps.filter(
      (s) => s.event_type === 'step_complete' && s.step_name.startsWith('model_'),
    )
  }, [reasoningSteps])

  const consensusResult = useMemo(() => {
    return reasoningSteps.find(
      (s) => s.event_type === 'consensus' && s.step_name === 'complete',
    )
  }, [reasoningSteps])

  if (modelOutputs.length === 0) {
    return (
      <div className="flex-1 flex items-center justify-center text-text-muted text-xs p-4">
        <div className="text-center">
          <p className="mb-1">No multi-model comparison data</p>
          <p className="text-text-muted/60">Use Debate or Research mode with consensus strategy to compare models</p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto p-3 space-y-3">
      <div className="grid gap-3" style={{ gridTemplateColumns: `repeat(${Math.min(modelOutputs.length, 3)}, 1fr)` }}>
        {modelOutputs.map((output, i) => (
          <div key={i} className="border border-border rounded-lg overflow-hidden">
            <div className="px-3 py-1.5 bg-surface-hover border-b border-border flex items-center justify-between">
              <span className="text-xs font-medium text-text-primary">{output.model || `Model ${i + 1}`}</span>
              {output.metadata?.tokens && (
                <span className="text-[10px] text-text-muted">{output.metadata.tokens as number} tok</span>
              )}
            </div>
            <div className="p-3 text-xs text-text-secondary leading-relaxed whitespace-pre-wrap max-h-[300px] overflow-y-auto">
              {output.content}
            </div>
          </div>
        ))}
      </div>

      {consensusResult && (
        <div className="border border-accent/30 rounded-lg overflow-hidden">
          <div className="px-3 py-1.5 bg-accent/10 border-b border-accent/20">
            <span className="text-xs font-medium text-accent">Consensus Synthesis</span>
          </div>
          <div className="p-3 text-xs text-text-secondary leading-relaxed whitespace-pre-wrap">
            {consensusResult.content}
          </div>
        </div>
      )}
    </div>
  )
}
