// web/src/components/markdown/CodeBlock.tsx
import { useState } from 'react'
import { Copy, Check, ChevronDown, ChevronUp } from 'lucide-react'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism'

interface Props {
  code: string
  language?: string
}

export function CodeBlock({ code, language }: Props) {
  const [copied, setCopied] = useState(false)
  const [expanded, setExpanded] = useState(false)

  const lines = code.split('\n')
  const isLong = lines.length > 30
  const displayCode = isLong && !expanded ? lines.slice(0, 15).join('\n') : code
  const lang = language || 'text'

  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="my-3 rounded-xl border border-code-border overflow-hidden bg-code-bg">
      <div className="flex items-center justify-between px-4 py-2 bg-surface-hover/50 border-b border-code-border">
        <span className="text-xs font-mono text-text-muted uppercase">{lang}</span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 text-xs text-text-muted hover:text-text-secondary transition-colors"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-cost-green" />
              Copied
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              Copy
            </>
          )}
        </button>
      </div>

      <SyntaxHighlighter
        language={lang}
        style={oneDark}
        customStyle={{
          margin: 0,
          padding: '1rem',
          background: 'transparent',
          fontSize: '13px',
          lineHeight: '1.6',
        }}
        showLineNumbers={lines.length > 5}
        lineNumberStyle={{ color: '#555570', fontSize: '11px', paddingRight: '1rem' }}
      >
        {displayCode}
      </SyntaxHighlighter>

      {isLong && (
        <button
          onClick={() => setExpanded(!expanded)}
          className="w-full flex items-center justify-center gap-1 py-2 text-xs text-text-muted hover:text-text-secondary border-t border-code-border transition-colors"
        >
          {expanded ? (
            <>
              <ChevronUp className="w-3 h-3" />
              Collapse
            </>
          ) : (
            <>
              <ChevronDown className="w-3 h-3" />
              Show all ({lines.length} lines)
            </>
          )}
        </button>
      )}
    </div>
  )
}

// web-solid/src/components/markdown/CodeBlock.tsx
import { createSignal, createResource, Show, createMemo } from 'solid-js'
import { codeToHtml } from 'shiki'
import { Copy, Check, ChevronDown, ChevronUp } from 'lucide-solid'

interface Props {
  code: string
  language?: string
}

export function CodeBlock(props: Props) {
  const [copied, setCopied] = createSignal(false)
  const [expanded, setExpanded] = createSignal(false)

  const lines = createMemo(() => props.code.split('\n'))
  const isLong = createMemo(() => lines().length > 30)
  const displayCode = createMemo(() =>
    isLong() && !expanded() ? lines().slice(0, 15).join('\n') : props.code,
  )
  const lang = createMemo(() => props.language || 'text')

  const source = createMemo(() => ({ code: displayCode(), lang: lang() }))

  const [highlighted] = createResource(source, async (src) => {
    return codeToHtml(src.code, {
      lang: src.lang,
      theme: 'one-dark-pro',
    })
  })

  const handleCopy = () => {
    navigator.clipboard.writeText(props.code)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div class="my-3 rounded-xl overflow-hidden" style={{ border: '1px solid oklch(0.30 0.03 185)', background: 'oklch(0.18 0.02 185)' }}>
      <div
        class="flex items-center justify-between px-4 py-2"
        style={{ background: 'oklch(0.22 0.025 185 / 0.5)', 'border-bottom': '1px solid oklch(0.30 0.03 185)' }}
      >
        <span class="text-xs font-mono uppercase" style={{ color: 'oklch(0.50 0.04 185)' }}>
          {lang()}
        </span>
        <button
          onClick={handleCopy}
          class="flex items-center gap-1.5 text-xs transition-colors"
          style={{ color: 'oklch(0.50 0.04 185)' }}
        >
          <Show when={copied()} fallback={<><Copy size={14} /> Copy</>}>
            <Check size={14} style={{ color: 'oklch(0.72 0.15 145)' }} /> Copied
          </Show>
        </button>
      </div>

      <Show
        when={!highlighted.loading && highlighted()}
        fallback={
          <pre
            class="p-4 overflow-x-auto"
            style={{ 'font-size': '13px', 'line-height': '1.6', color: 'oklch(0.85 0.02 185)', 'font-family': 'var(--font-mono)' }}
          >
            <code>{displayCode()}</code>
          </pre>
        }
      >
        <div
          class="overflow-x-auto [&_pre]:!bg-transparent [&_pre]:!m-0 [&_pre]:!p-4"
          style={{ 'font-size': '13px', 'line-height': '1.6' }}
          innerHTML={highlighted()!}
        />
      </Show>

      <Show when={isLong()}>
        <button
          onClick={() => setExpanded(!expanded())}
          class="w-full flex items-center justify-center gap-1 py-2 text-xs transition-colors"
          style={{ color: 'oklch(0.50 0.04 185)', 'border-top': '1px solid oklch(0.30 0.03 185)' }}
        >
          <Show when={expanded()} fallback={<><ChevronDown size={12} /> Show all ({lines().length} lines)</>}>
            <ChevronUp size={12} /> Collapse
          </Show>
        </button>
      </Show>
    </div>
  )
}
