// web-solid/src/components/chat/EmilyMessage.tsx
import { createSignal, createMemo, Show, For } from 'solid-js'
import {
  Copy, Check, ThumbsUp, ThumbsDown, RotateCcw,
  Brain, Volume2, Square, Sparkles, ChevronDown, ChevronRight, Globe,
} from 'lucide-solid'
import { MarkdownRenderer } from '../markdown/MarkdownRenderer'
import { rateMessage } from '../../stores/chat'
import { formatCost, formatLatency } from '../../lib/cost'
import { PROVIDER_COLORS } from '../../api/types'
import { API_BASE } from '../../lib/env'
import type { Message } from '../../api/types'

interface Props {
  message?: Message
  streaming?: boolean
  streamText?: string
  streamThinking?: string
  model?: string
  provider?: string
  searchSources?: Array<{ title: string; url: string }>
}

export function EmilyMessage(props: Props) {
  const [copied, setCopied] = createSignal(false)
  const [speaking, setSpeaking] = createSignal(false)
  const [thinkingCollapsed, setThinkingCollapsed] = createSignal(false)
  let audioRef: HTMLAudioElement | null = null

  const content = createMemo(() =>
    props.streaming ? (props.streamText ?? '') : (props.message?.content ?? ''),
  )
  const thinking = createMemo(() =>
    props.streaming ? (props.streamThinking ?? '') : (props.message?.thinking_content ?? ''),
  )
  const displayModel = createMemo(() => props.model || props.message?.model || '')
  const displayProvider = createMemo(() => props.provider || props.message?.provider || '')

  const handleCopy = () => {
    navigator.clipboard.writeText(content())
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  const handleSpeak = async () => {
    if (speaking()) {
      audioRef?.pause()
      if (audioRef) audioRef.currentTime = 0
      setSpeaking(false)
      return
    }
    const text = content().trim()
    if (!text) return

    setSpeaking(true)
    try {
      const res = await fetch(`${API_BASE}/api/v1/tts/speak`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text }),
      })
      if (!res.ok) throw new Error(`TTS failed: ${res.status}`)

      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const audio = new Audio(url)
      audioRef = audio
      audio.onended = () => {
        setSpeaking(false)
        URL.revokeObjectURL(url)
      }
      audio.onerror = () => {
        setSpeaking(false)
        URL.revokeObjectURL(url)
      }
      await audio.play()
    } catch {
      setSpeaking(false)
    }
  }

  return (
    <div class="flex group gap-2.5 items-start">
      {/* Emily avatar */}
      <div
        class="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
        style={{
          background: 'oklch(0.72 0.17 162 / 0.12)',
          border: '1px solid oklch(0.72 0.17 162 / 0.28)',
        }}
      >
        <Sparkles size={14} style={{ color: 'oklch(0.72 0.17 162)' }} />
      </div>

      <div class="max-w-[82%] min-w-0 space-y-1.5">
        {/* Name label */}
        <span
          style={{
            'font-size': 'var(--text-small)',
            'font-weight': '600',
            'font-family': 'var(--font-display)',
            color: 'oklch(0.72 0.17 162)',
          }}
        >
          Emily
        </span>

        <Show when={thinking()}>
          <div
            class="rounded-xl overflow-hidden"
            style={{
              border: '1px solid oklch(0.32 0.05 200)',
              background: 'oklch(0.19 0.025 200)',
            }}
          >
            <button
              onClick={() => !props.streaming && setThinkingCollapsed(!thinkingCollapsed())}
              class="w-full flex items-center gap-2 px-3 py-2 transition-colors"
              style={{
                'font-size': 'var(--text-small)',
                color: 'oklch(0.72 0.17 162)',
                'font-family': 'var(--font-body)',
                'font-weight': '500',
              }}
            >
              <Show when={!props.streaming}>
                <Show when={thinkingCollapsed()} fallback={<ChevronDown size={12} class="flex-shrink-0" />}>
                  <ChevronRight size={12} class="flex-shrink-0" />
                </Show>
              </Show>
              <Brain size={14} class="flex-shrink-0" />
              <span>Thinking</span>
              <span class="font-normal ml-1" style={{ color: 'oklch(0.50 0.04 185)' }}>
                ~{Math.round(thinking().length / 4).toLocaleString()} tokens
              </span>
              <Show when={props.streaming}>
                <span class="flex items-center gap-1.5 ml-auto">
                  <span
                    class="w-1.5 h-1.5 rounded-full animate-pulse"
                    style={{ background: 'oklch(0.72 0.17 162)' }}
                  />
                  <span style={{ 'font-size': '0.625rem', color: 'oklch(0.50 0.04 185)', 'font-family': 'var(--font-mono)' }}>
                    live
                  </span>
                </span>
              </Show>
            </button>
            <Show when={!thinkingCollapsed()}>
              <div class="px-3 pb-3" style={{ 'border-top': '1px solid oklch(0.32 0.05 200 / 0.5)' }}>
                <div
                  class="leading-relaxed whitespace-pre-wrap max-h-64 overflow-y-auto mt-2"
                  style={{ 'font-size': 'var(--text-small)', color: 'oklch(0.50 0.04 185)', 'font-family': 'var(--font-body)' }}
                >
                  {thinking()}
                  <Show when={props.streaming}>
                    <span
                      class="inline-block w-1 h-3 animate-pulse ml-0.5 -mb-0.5 rounded-sm"
                      style={{ background: 'oklch(0.72 0.17 162)' }}
                    />
                  </Show>
                </div>
              </div>
            </Show>
          </div>
        </Show>

        <div
          class="rounded-2xl rounded-tl-sm px-4 py-3"
          style={{
            background: 'oklch(0.20 0.02 185)',
            border: '1px solid oklch(0.30 0.03 185 / 0.5)',
          }}
        >
          <Show
            when={content()}
            fallback={
              <Show when={props.streaming}>
                <div
                  class="flex items-center gap-2"
                  style={{ color: 'oklch(0.50 0.04 185)', 'font-size': 'var(--text-body)', 'font-family': 'var(--font-body)' }}
                >
                  <span class="flex gap-1">
                    <span class="w-1.5 h-1.5 rounded-full animate-bounce" style={{ background: 'oklch(0.72 0.17 162)', 'animation-delay': '0ms' }} />
                    <span class="w-1.5 h-1.5 rounded-full animate-bounce" style={{ background: 'oklch(0.72 0.17 162)', 'animation-delay': '150ms' }} />
                    <span class="w-1.5 h-1.5 rounded-full animate-bounce" style={{ background: 'oklch(0.72 0.17 162)', 'animation-delay': '300ms' }} />
                  </span>
                  Emily is thinking...
                </div>
              </Show>
            }
          >
            <MarkdownRenderer content={content()} />
          </Show>
        </div>

        {/* Search sources */}
        <Show when={props.searchSources && props.searchSources.length > 0}>
          <div class="flex flex-wrap gap-1.5 px-1">
            <For each={props.searchSources}>
              {(s) => (
                <a
                  href={s.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="flex items-center gap-1 px-2 py-0.5 rounded-full transition-colors"
                  style={{
                    'font-size': 'var(--text-small)',
                    color: 'oklch(0.65 0.03 185)',
                    background: 'oklch(0.18 0.02 185)',
                    border: '1px solid oklch(0.30 0.03 185)',
                    'font-family': 'var(--font-body)',
                  }}
                >
                  <Globe size={12} />
                  <span class="max-w-[150px] truncate">{s.title}</span>
                </a>
              )}
            </For>
          </div>
        </Show>

        {/* Action bar */}
        <div class="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity pl-1">
          <Show when={displayModel()}>
            <div
              class="flex items-center gap-1.5 mr-2"
              style={{ 'font-size': 'var(--text-small)', color: 'oklch(0.50 0.04 185)', 'font-family': 'var(--font-mono)' }}
            >
              <span
                class="w-1.5 h-1.5 rounded-full"
                style={{ 'background-color': PROVIDER_COLORS[displayProvider()] || 'oklch(0.50 0.04 185)' }}
              />
              <span>{displayModel()}</span>
            </div>
          </Show>

          <Show when={props.message && !props.streaming}>
            <Show when={props.message!.latency_ms != null}>
              <span
                class="mr-1"
                style={{ 'font-size': 'var(--text-small)', color: 'oklch(0.50 0.04 185)', 'font-family': 'var(--font-mono)' }}
              >
                {formatLatency(props.message!.latency_ms!)}
              </span>
            </Show>
            <Show when={props.message!.cost_usd > 0}>
              <span
                class="mr-1"
                style={{ 'font-size': 'var(--text-small)', color: 'oklch(0.72 0.15 145)', 'font-family': 'var(--font-mono)' }}
              >
                {formatCost(props.message!.cost_usd)}
              </span>
            </Show>
          </Show>

          <div class="flex items-center gap-0.5 ml-auto">
            <Show when={content() && !props.streaming}>
              <button
                onClick={handleSpeak}
                class="p-1 rounded-md transition-colors"
                style={{
                  color: speaking() ? 'oklch(0.72 0.17 162)' : 'oklch(0.50 0.04 185)',
                  background: speaking() ? 'oklch(0.72 0.17 162 / 0.10)' : '',
                }}
                title={speaking() ? 'Stop reading' : 'Read aloud'}
              >
                <Show when={speaking()} fallback={<Volume2 size={14} />}>
                  <Square size={14} />
                </Show>
              </button>
            </Show>

            <button
              onClick={handleCopy}
              class="p-1 rounded-md transition-colors"
              style={{ color: 'oklch(0.50 0.04 185)' }}
              title="Copy"
            >
              <Show when={copied()} fallback={<Copy size={14} />}>
                <Check size={14} style={{ color: 'oklch(0.72 0.15 145)' }} />
              </Show>
            </button>

            <Show when={props.message && !props.streaming}>
              <button
                onClick={() => rateMessage(props.message!.id, props.message!.rating === 1 ? 0 : 1)}
                class="p-1 rounded-md transition-colors"
                style={{
                  color: props.message!.rating === 1 ? 'oklch(0.72 0.15 145)' : 'oklch(0.50 0.04 185)',
                  background: props.message!.rating === 1 ? 'oklch(0.72 0.15 145 / 0.10)' : '',
                }}
                title="Good response"
              >
                <ThumbsUp size={14} />
              </button>
              <button
                onClick={() => rateMessage(props.message!.id, props.message!.rating === -1 ? 0 : -1)}
                class="p-1 rounded-md transition-colors"
                style={{
                  color: props.message!.rating === -1 ? 'oklch(0.65 0.20 25)' : 'oklch(0.50 0.04 185)',
                  background: props.message!.rating === -1 ? 'oklch(0.65 0.20 25 / 0.10)' : '',
                }}
                title="Bad response"
              >
                <ThumbsDown size={14} />
              </button>
              <button
                class="p-1 rounded-md transition-colors"
                style={{ color: 'oklch(0.50 0.04 185)' }}
                title="Retry"
              >
                <RotateCcw size={14} />
              </button>
            </Show>
          </div>
        </div>
      </div>
    </div>
  )
}

// web/src/components/chat/EmilyMessage.tsx
import { useState, useRef, useCallback } from 'react'
import { API_BASE } from '../../lib/env'
import {
  Copy, Check, ThumbsUp, ThumbsDown, RotateCcw,
  Brain, Volume2, Square, Sparkles, ChevronDown, ChevronRight, Globe,
} from 'lucide-react'
import { MarkdownRenderer } from '../markdown/MarkdownRenderer'
import { useChatStore } from '../../stores/chat'
import { formatCost, formatLatency } from '../../lib/cost'
import { PROVIDER_COLORS } from '../../api/types'
import type { Message } from '../../api/types'

interface Props {
  message?: Message
  streaming?: boolean
  streamText?: string
  streamThinking?: string
  model?: string
  provider?: string
  searchSources?: Array<{ title: string; url: string }>
}

export function EmilyMessage({ message, streaming, streamText, streamThinking, model, provider, searchSources }: Props) {
  const rateMessage = useChatStore((s) => s.rateMessage)
  const [copied, setCopied] = useState(false)
  const [speaking, setSpeaking] = useState(false)
  const [thinkingCollapsed, setThinkingCollapsed] = useState(false)
  const audioRef = useRef<HTMLAudioElement | null>(null)

  const content = streaming ? streamText || '' : message?.content || ''
  const thinking = streaming ? streamThinking || '' : message?.thinking_content || ''
  const displayModel = model || message?.model || ''
  const displayProvider = provider || message?.provider || ''

  const handleCopy = () => {
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  const handleSpeak = useCallback(async () => {
    if (speaking) {
      audioRef.current?.pause()
      if (audioRef.current) audioRef.current.currentTime = 0
      setSpeaking(false)
      return
    }
    if (!content.trim()) return

    setSpeaking(true)
    try {
      const res = await fetch(`${API_BASE}/api/v1/tts/speak`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: content }),
      })
      if (!res.ok) throw new Error(`TTS failed: ${res.status}`)

      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const audio = new Audio(url)
      audioRef.current = audio
      audio.onended = () => {
        setSpeaking(false)
        URL.revokeObjectURL(url)
      }
      audio.onerror = () => {
        setSpeaking(false)
        URL.revokeObjectURL(url)
      }
      await audio.play()
    } catch {
      setSpeaking(false)
    }
  }, [content, speaking])

  return (
    <div className="flex group gap-2.5 items-start">
      {/* Emily avatar */}
      <div className="w-7 h-7 rounded-full bg-accent/15 border border-accent/30 flex items-center justify-center flex-shrink-0 mt-0.5">
        <Sparkles className="w-3.5 h-3.5 text-accent" />
      </div>

      <div className="max-w-[82%] min-w-0 space-y-1.5">
        {/* Name label */}
        <span className="text-xs font-semibold text-accent">Emily</span>

        {thinking && (
          <div className="border border-thinking-border bg-thinking-bg rounded-xl overflow-hidden">
            <button
              onClick={() => !streaming && setThinkingCollapsed(!thinkingCollapsed)}
              className="w-full flex items-center gap-2 px-3 py-2 text-xs text-phase-analyzing font-medium hover:bg-white/[0.02] transition-colors"
            >
              {!streaming && (thinkingCollapsed
                ? <ChevronRight className="w-3 h-3 flex-shrink-0" />
                : <ChevronDown className="w-3 h-3 flex-shrink-0" />
              )}
              <Brain className="w-3.5 h-3.5 flex-shrink-0" />
              <span>Thinking</span>
              <span className="text-text-muted font-normal ml-1">
                ~{Math.round(thinking.length / 4).toLocaleString()} tokens
              </span>
              {streaming && (
                <span className="flex items-center gap-1.5 ml-auto">
                  <span className="w-1.5 h-1.5 rounded-full bg-phase-analyzing animate-pulse" />
                  <span className="text-[10px] text-text-muted font-normal">live</span>
                </span>
              )}
            </button>
            {!thinkingCollapsed && (
              <div className="px-3 pb-3 border-t border-thinking-border/50">
                <div className="text-xs text-text-muted leading-relaxed whitespace-pre-wrap max-h-64 overflow-y-auto mt-2">
                  {thinking}
                  {streaming && (
                    <span className="inline-block w-1 h-3 bg-phase-analyzing animate-pulse ml-0.5 -mb-0.5 rounded-sm" />
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        <div className="bg-emily-bubble rounded-2xl rounded-tl-md px-4 py-3 border border-border/50">
          {content ? (
            <MarkdownRenderer content={content} />
          ) : streaming ? (
            <div className="flex items-center gap-2 text-text-muted text-sm">
              <span className="flex gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-accent animate-bounce" style={{ animationDelay: '0ms' }} />
                <span className="w-1.5 h-1.5 rounded-full bg-accent animate-bounce" style={{ animationDelay: '150ms' }} />
                <span className="w-1.5 h-1.5 rounded-full bg-accent animate-bounce" style={{ animationDelay: '300ms' }} />
              </span>
              Emily is thinking...
            </div>
          ) : null}
        </div>

        {/* Search sources */}
        {searchSources && searchSources.length > 0 && (
          <div className="flex flex-wrap gap-1.5 px-1">
            {searchSources.map((s, i) => (
              <a
                key={i}
                href={s.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 px-2 py-0.5 rounded-full bg-surface border border-border text-xs text-text-secondary hover:text-accent hover:border-accent/30 transition-colors"
              >
                <Globe className="w-3 h-3" />
                <span className="max-w-[150px] truncate">{s.title}</span>
              </a>
            ))}
          </div>
        )}

        {/* Action bar */}
        <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity pl-1">
          {displayModel && (
            <div className="flex items-center gap-1.5 text-xs text-text-muted mr-2">
              <span
                className="w-1.5 h-1.5 rounded-full"
                style={{ backgroundColor: PROVIDER_COLORS[displayProvider] || '#555' }}
              />
              <span>{displayModel}</span>
            </div>
          )}

          {message && !streaming && (
            <>
              {message.latency_ms != null && (
                <span className="text-xs text-text-muted mr-1">{formatLatency(message.latency_ms)}</span>
              )}
              {message.cost_usd > 0 && (
                <span className="text-xs text-cost-green mr-1">{formatCost(message.cost_usd)}</span>
              )}
            </>
          )}

          <div className="flex items-center gap-0.5 ml-auto">
            {content && !streaming && (
              <button
                onClick={handleSpeak}
                className={`p-1 rounded-md transition-colors ${speaking ? 'text-accent bg-accent/10' : 'text-text-muted hover:text-text-secondary hover:bg-surface-hover'}`}
                title={speaking ? 'Stop reading' : 'Read aloud'}
              >
                {speaking ? <Square className="w-3.5 h-3.5" /> : <Volume2 className="w-3.5 h-3.5" />}
              </button>
            )}

            <button
              onClick={handleCopy}
              className="p-1 rounded-md text-text-muted hover:text-text-secondary hover:bg-surface-hover transition-colors"
              title="Copy"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-cost-green" /> : <Copy className="w-3.5 h-3.5" />}
            </button>

            {message && !streaming && (
              <>
                <button
                  onClick={() => rateMessage(message.id, message.rating === 1 ? 0 : 1)}
                  className={`p-1 rounded-md transition-colors ${message.rating === 1 ? 'text-cost-green bg-cost-green/10' : 'text-text-muted hover:text-text-secondary hover:bg-surface-hover'}`}
                  title="Good response"
                >
                  <ThumbsUp className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => rateMessage(message.id, message.rating === -1 ? 0 : -1)}
                  className={`p-1 rounded-md transition-colors ${message.rating === -1 ? 'text-error-red bg-error-red/10' : 'text-text-muted hover:text-text-secondary hover:bg-surface-hover'}`}
                  title="Bad response"
                >
                  <ThumbsDown className="w-3.5 h-3.5" />
                </button>
                <button className="p-1 rounded-md text-text-muted hover:text-text-secondary hover:bg-surface-hover transition-colors" title="Retry">
                  <RotateCcw className="w-3.5 h-3.5" />
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
