// web-solid/src/components/common/ErrorBoundary.tsx
import { ErrorBoundary as SolidErrorBoundary, type JSX } from 'solid-js'
import { AlertTriangle, RefreshCw } from 'lucide-solid'

interface Props {
  children: JSX.Element
}

export function ErrorBoundary(props: Props) {
  return (
    <SolidErrorBoundary
      fallback={(err: Error, reset) => (
        <div class="flex items-center justify-center h-full" style={{ background: 'oklch(0.18 0.02 185)' }}>
          <div class="text-center space-y-4 max-w-md p-8">
            <AlertTriangle size={48} style={{ color: 'oklch(0.75 0.16 85)', margin: '0 auto' }} />
            <h2 class="text-lg font-semibold" style={{ color: 'oklch(0.93 0.01 90)' }}>
              Something went wrong
            </h2>
            <p class="text-sm" style={{ color: 'oklch(0.65 0.03 185)' }}>
              {err.message}
            </p>
            <button
              onClick={() => {
                reset()
                window.location.reload()
              }}
              class="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition-colors"
              style={{ background: 'oklch(0.72 0.17 162)', color: 'oklch(0.18 0.02 185)' }}
            >
              <RefreshCw size={16} />
              Reload
            </button>
          </div>
        </div>
      )}
    >
      {props.children}
    </SolidErrorBoundary>
  )
}

// web/src/components/common/ErrorBoundary.tsx
import { Component, type ReactNode } from 'react'
import { AlertTriangle, RefreshCw } from 'lucide-react'

interface Props {
  children: ReactNode
}

interface State {
  hasError: boolean
  error: Error | null
}

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = { hasError: false, error: null }
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error }
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="flex items-center justify-center h-full bg-surface">
          <div className="text-center space-y-4 max-w-md p-8">
            <AlertTriangle className="w-12 h-12 text-warning-amber mx-auto" />
            <h2 className="text-lg font-semibold text-text-primary">Something went wrong</h2>
            <p className="text-sm text-text-secondary">{this.state.error?.message}</p>
            <button
              onClick={() => {
                this.setState({ hasError: false, error: null })
                window.location.reload()
              }}
              className="inline-flex items-center gap-2 px-4 py-2 bg-accent hover:bg-accent-hover text-white rounded-lg text-sm transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              Reload
            </button>
          </div>
        </div>
      )
    }

    return this.props.children
  }
}
