// web-solid/src/components/layout/MainLayout.tsx
import { createEffect, onMount, Show, Switch, Match } from 'solid-js'
import { Sidebar } from './Sidebar'
import { TopBar } from './TopBar'
import { MessageList } from '../chat/MessageList'
import { InputPanel } from '../chat/InputPanel'
import { EmptyState } from '../chat/EmptyState'
import { ErrorBoundary } from '../common/ErrorBoundary'
import { LoginScreen } from '../auth/LoginScreen'
import { SearchOverlay } from '../search/SearchOverlay'
import { ModeSelector } from '../chat/ModeSelector'
import { BrainPage } from '../../pages/BrainPage'
import { SettingsPage } from '../../pages/SettingsPage'
import { VoicePage } from '../../pages/VoicePage'
import { VisionPage } from '../../pages/VisionPage'
import { LogsPage } from '../../pages/LogsPage'
import { TerminalPage } from '../../pages/TerminalPage'
import {
  uiState, setAuthenticated, setRightPanelVisible, setReasoningPanelSize,
} from '../../stores/ui'
import { chatState } from '../../stores/chat'
import { createModeAccent } from '../../primitives/createModeAccent'
import { createKeyboard } from '../../primitives/createKeyboard'
import { API_RAW } from '../../lib/env'

export function MainLayout() {
  createModeAccent()
  createKeyboard()

  let prevThinking = ''

  // Auto-open reasoning panel when thinking content arrives
  createEffect(() => {
    const thinking = chatState.streamingThinking
    if (thinking && !prevThinking) {
      setRightPanelVisible(true)
      if (uiState.reasoningPanelSize === 'hidden') {
        setReasoningPanelSize('sidebar')
      }
    }
    prevThinking = thinking
  })

  // Auth check on mount
  onMount(() => {
    fetch(`${API_RAW}/settings/auth/status`)
      .then((r) => r.json())
      .then((d: { passphrase_set?: boolean; has_owner?: boolean }) => {
        if (!d.passphrase_set || !d.has_owner) {
          setAuthenticated(true)
        }
      })
      .catch(() => setAuthenticated(true))
  })

  return (
    <Show when={uiState.authenticated} fallback={<LoginScreen />}>
      <div class="flex h-screen w-screen overflow-hidden" style={{ background: 'oklch(0.18 0.02 185)' }}>
        <Show when={uiState.activePage === 'chat'}>
          <aside>
            <Sidebar />
          </aside>
        </Show>

        <main class="flex flex-1 flex-col min-w-0">
          <header>
            <TopBar />
          </header>

          <Switch fallback={
            <div class="flex flex-1 min-h-0">
              <div class="flex flex-1 flex-col min-w-0">
                <Show when={chatState.activeId} fallback={<EmptyState />}>
                  <MessageList />
                  <InputPanel />
                </Show>
              </div>
            </div>
          }>
            <Match when={uiState.activePage === 'chat'}>
              <div class="flex flex-1 min-h-0">
                <div class="flex flex-1 flex-col min-w-0">
                  <Show when={chatState.activeId} fallback={<EmptyState />}>
                    <MessageList />
                    <InputPanel />
                  </Show>
                </div>
              </div>
            </Match>
            <Match when={uiState.activePage === 'voice'}>
              <ErrorBoundary>
                <VoicePage />
              </ErrorBoundary>
            </Match>
            <Match when={uiState.activePage === 'vision'}>
              <ErrorBoundary>
                <VisionPage />
              </ErrorBoundary>
            </Match>
            <Match when={uiState.activePage === 'logs'}>
              <ErrorBoundary>
                <LogsPage />
              </ErrorBoundary>
            </Match>
            <Match when={uiState.activePage === 'brain'}>
              <ErrorBoundary>
                <BrainPage />
              </ErrorBoundary>
            </Match>
            <Match when={uiState.activePage === 'terminal'}>
              <ErrorBoundary>
                <TerminalPage />
              </ErrorBoundary>
            </Match>
            <Match when={uiState.activePage === 'settings'}>
              <ErrorBoundary>
                <SettingsPage />
              </ErrorBoundary>
            </Match>
          </Switch>
        </main>

        {/* Overlays */}
        <Show when={uiState.searchOpen}>
          <SearchOverlay />
        </Show>
        <ModeSelector />
      </div>
    </Show>
  )
}

// web/src/components/layout/MainLayout.tsx
import { useEffect, useRef, useState } from 'react'
import { Sidebar } from './Sidebar'
import { TopBar } from './TopBar'
import { MessageList } from '../chat/MessageList'
import { InputPanel } from '../chat/InputPanel'
import { ReasoningPanelV2 } from '../reasoning/ReasoningPanelV2'
import { SearchOverlay } from '../search/SearchOverlay'
import { ModeSelector } from '../chat/ModeSelector'
import { LoginScreen } from '../auth/LoginScreen'
import { OnboardingFlow } from '../auth/OnboardingFlow'
import { useUIStore } from '../../stores/ui'
import { useChatStore } from '../../stores/chat'
import { EmptyState } from '../chat/EmptyState'
import { ErrorBoundary } from '../common/ErrorBoundary'
import { VoicePage } from '../../pages/VoicePage'
import { VisionPage } from '../../pages/VisionPage'
import { LogsPage } from '../../pages/LogsPage'
import { BrainPage } from '../../pages/BrainPage'
import { TerminalPage } from '../../pages/TerminalPage'
import { SettingsPage } from '../../pages/SettingsPage'
import { API_RAW } from '../../lib/env'
import { useModeAccent } from '../../hooks/useModeAccent'

const API = API_RAW

const PANEL_WIDTH_CLASS: Record<string, string> = {
  sidebar: 'w-80',
  half: 'w-[50vw]',
  fullscreen: '', // handled separately as overlay
  hidden: '',
}

export function MainLayout() {
  useModeAccent()
  const rightPanelVisible = useUIStore((s) => s.rightPanelVisible)
  const setRightPanelVisible = useUIStore((s) => s.setRightPanelVisible)
  const reasoningPanelSize = useUIStore((s) => s.reasoningPanelSize)
  const setReasoningPanelSize = useUIStore((s) => s.setReasoningPanelSize)
  const searchOpen = useUIStore((s) => s.searchOpen)
  const activePage = useUIStore((s) => s.activePage)
  const authenticated = useUIStore((s) => s.authenticated)
  const setAuthenticated = useUIStore((s) => s.setAuthenticated)
  const activeId = useChatStore((s) => s.activeId)
  const streamingThinking = useChatStore((s) => s.streamingThinking)
  const prevThinkingRef = useRef('')
  const [needsOnboarding, setNeedsOnboarding] = useState(false)

  // Auto-open reasoning panel the first time thinking content arrives in a stream
  useEffect(() => {
    if (streamingThinking && !prevThinkingRef.current) {
      setRightPanelVisible(true)
      if (reasoningPanelSize === 'hidden') {
        setReasoningPanelSize('sidebar')
      }
    }
    prevThinkingRef.current = streamingThinking
  }, [streamingThinking, setRightPanelVisible, reasoningPanelSize, setReasoningPanelSize])

  // Route to onboarding if no owner, skip login if no passphrase set
  useEffect(() => {
    fetch(`${API}/settings/auth/status`)
      .then((r) => r.json())
      .then((d) => {
        if (!d.has_owner) {
          setNeedsOnboarding(true)
        } else if (!d.passphrase_set) {
          setAuthenticated(true)
        }
      })
      .catch(() => setAuthenticated(true)) // API unreachable → let through
  }, [setAuthenticated])

  if (needsOnboarding) {
    return (
      <OnboardingFlow
        onComplete={() => {
          setNeedsOnboarding(false)
          setAuthenticated(true)
        }}
      />
    )
  }

  if (!authenticated) return <LoginScreen />

  const renderPage = () => {
    switch (activePage) {
      case 'voice': return <VoicePage />
      case 'vision': return <VisionPage />
      case 'logs': return <LogsPage />
      case 'brain': return <BrainPage />
      case 'terminal': return <TerminalPage />
      case 'settings': return <SettingsPage />
      case 'chat':
      default:
        return (
          <div className="flex flex-1 min-h-0">
            <div className="flex flex-1 flex-col min-w-0">
              {activeId ? (
                <>
                  <MessageList />
                  <InputPanel />
                </>
              ) : (
                <EmptyState />
              )}
            </div>
            {rightPanelVisible && reasoningPanelSize !== 'fullscreen' && reasoningPanelSize !== 'hidden' && (
              <aside
                aria-label="Reasoning"
                className={`${PANEL_WIDTH_CLASS[reasoningPanelSize]} border-l border-border flex-shrink-0 overflow-hidden`}
              >
                <ErrorBoundary>
                  <ReasoningPanelV2 />
                </ErrorBoundary>
              </aside>
            )}
            {reasoningPanelSize === 'fullscreen' && (
              <div className="fixed inset-0 z-50 bg-surface/95 backdrop-blur-sm flex flex-col">
                <ErrorBoundary>
                  <ReasoningPanelV2 />
                </ErrorBoundary>
              </div>
            )}
          </div>
        )
    }
  }

  return (
    <div className="flex h-screen w-screen overflow-hidden bg-surface">
      {activePage === 'chat' && (
        <aside aria-label="Conversations">
          <Sidebar />
        </aside>
      )}

      <main className="flex flex-1 flex-col min-w-0">
        <header>
          <TopBar />
        </header>
        {renderPage()}
      </main>

      {searchOpen && <SearchOverlay />}
      <ModeSelector />
    </div>
  )
}
